### ISSUE TITLE
Implement Type Check for `//`

### ISSUE THREAD

**Issue by FintanH** [Nadrieril/dhall-rust#86]
The implementation of type-checking `Prefer`/`RightBiasedRecordMerge`. All type-checking happens in `typecheck.rs`.

**Comment by Nadrieril** [comment]
Did you manage to get everything up and running ? Did you manage to run the tests successfully ? I know it can be tricky if you're not familiar with rust and git; I should write instructions somewhere

**Comment by FintanH** [comment]
Hey! Thanks for checking in :) I got things up and running with nix and was able to enable the tests for `RightBiasedRecordMerge` and see them fail. I just haven't gotten around to actually looking at/writing code :sweat_smile: 

I could probably add some contribution instructions to help with getting up and running :grin:

**Comment by Nadrieril** [comment]
Yeah that would be very helpful !

**Comment by FintanH** [comment]
Ok, I'm starting to trash a bit now. I've been messing around and this is what I've come up with so far:

```rust
BinOp(o @ RightBiasedRecordMerge, l, r) => {
    let kvs_x = match l.get_type()?.get_value()? {
        Value::RecordLit(kvs) => kvs,
        _ => return Err(mkerr(BinOpTypeMismatch(*o, l.clone()))),
    };

    let kvs_y = match r.get_type()?.get_value()? {
        Value::RecordLit(kvs) => kvs,
        _ => return Err(mkerr(BinOpTypeMismatch(*o, l.clone()))),
    };

    // Union the two records, prefering
    // the values found in the RHS.
    for (label, value) in kvs_y {
        kvs_x.insert(label, value);
    }

    Ok(RetTypeOnly(tck_record_type(
        ctx,
        kvs_x.iter()
             .map(|(x, v)| Ok((x.clone(), v.get_type()?.into_owned()))),
    )?
    .into_type()))
}
```

I tried to crib some type checking of `RecordLit` here, but realised there's two `RecordLit`s, one a `Value` and one an `ExprF`. I'll be honest, that's a bit confusing 😅 So I'm wondering how should I go about type checking this value, or maybe there's a better idiom in this codebase I've missed.

Is there a good way of getting an overview of the codebase in general? Like generate the docs and look at the types and docs?

**Comment by Nadrieril** [comment]
Sadly the docs won't be much help since all of the things you are interested about are internals and so not exposed in the public API. I completely agee that this codebase is confusing, sorry :/
What I should do is write a guide that explains how the codebase works. In the meantime, I'll try to explain anything you need.

ExprF and Value do seem to overlap a lot, and here's why: ExprF is for the syntax and Value for the semantics. That means that the input is first parsed into something that uses ExprF, then converted into a Value during normalization and/or typechecking. After normalization, it can be converted back into ExprF if we want to print it out or encode it in binary. The reason those two things are different is that they have different requirements: for example ExprF needs to know about the different ways of expressing a union literal but Value doesn't; or a Value can store the type of some subterms but ExprF can't.

Then there are various wrappers around Values; in particular a `Thunk` just contains a `Value`, but in a way that avoids normalizing the same thing more than once. And a `Typed` is just a `Thunk` with a type.
The input to `type_last_layer` is a subtle mix of ExprF and Value: it is a single level of ExprF whose children are all Typed. That means that the children have already been typechecked but the top layer hasn't. In your example, `l` and `r` are `Typed`, which is why you can call `.get_type()` on them to get their type.

The trickiness in typechecking is that we need to not mix the terms and their types. It's particularly tricky because a type in dhall is itself a term.
Let's take an example: `let l : { x: Natural } = { x = 1 } in l.x`. Here `l` is a variable, and its type is `{ x: Natural }`. `{ x: Natural }` is itself a term, more precisely a record type. So in the code, `l` will be a `Value::Var`, and `l.get_type()` will be a `Value::RecordType`.
Your code is doing almost what's needed, except you're asking whether `l.get_type()` is a record literal. That's mixing the levels: `l` itself might be a record literal (or something that normalizes to a record literal), but the type of `l` can't be a record literal; we want it to be a record type. Once you fix that, you'll have what you need to make it work. I'd recommend debugging with `println!()` or `dbg!()` if you're not already doing that.

I hope that's a bit clearer. What else did you find confusing ? I can go into more detail about the whole thing with `Thunk`s and `Value`s.

**Comment by FintanH** [comment]
Thanks for the explanation! I believe it makes sense but I'll have to probably read it a couple of times :)

> all of the things you are interested about are internals and so not exposed in the public API

Should there be an effort to have a public API and a developer API? Something like the `dhall-haskell` implementation where it has the top level module `Dhall` but then the rest of the modules also have docs to peruse.

I was originally confused about this:
> That's mixing the levels: `l` itself might be a record literal (or something that normalizes to a record literal), but the type of `l` can't be a record literal; we want it to be a record type.

but I think I get it now. What's the process for normalizing an incoming parameter recursively? Because I believe I want something like this (in pseudo-code):
```
left_record = normalize(l)
right_record = normaliz(r)
result = right_based_union(l, r)
typecheck(result)
```

> I'd recommend debugging with println!() or dbg!() if you're not already doing that.

I'll try do that, but I've been mostly trying to follow types and grok the interfaces for them. Which, to be fair, got me some of the way 😁

**Comment by Nadrieril** [comment]
You're right, it looks like a good idea to make a separate crate for the public API. I'll add it to the TODO list.

> What's the process for normalizing an incoming parameter recursively?

Whenever you get a Value, it's already normalized enough, so you can just act as if it's completely normalized and not worry about that. Why do you ask ?

**Comment by FintanH** [comment]
Ok, I'm getting somewhere! I actually messed up pasting the code above because I was making changes even while I was asking the question :flushed: 

So I have the code below, quite similar to before, but as you said works over the types. Something that it cannot manage to do right now is make sure that we can't do `{ x = Text } // { y = 1 }`. I think disallowing this would involve kind checking `l` and `r` and saying that `Kind != Type`. Does that sound right? :thinking: What's the way to do this? 

```rust
BinOp(o @ RightBiasedRecordMerge, l, r) => {
    let mut kvs_x = match l.get_type()?.to_value() {
        Value::RecordType(kts) => kts,
        _ => return Err(mkerr(BinOpTypeMismatch(*o, l.clone()))),
    };

    let kvs_y = match r.get_type()?.to_value() {
        Value::RecordType(kts) => kts,
        _ => return Err(mkerr(BinOpTypeMismatch(*o, l.clone()))),
    };

    // Union the two records, prefering
    // the values found in the RHS.
    for (label, value) in kvs_y {
        kvs_x.insert(label, value);
    }

    Ok(RetTypeOnly(tck_record_type(
        ctx,
        kvs_x.iter()
             .map(|(x, v)| Ok((x.clone(), v.to_type()))),
    )?
    .into_type()))
}
```

**Comment by Nadrieril** [comment]
@FintanH Yep you're right. Getting the kind of `l` is easy: it's the type of its type, so you get it with `l.get_type()?.get_type()?`. Then you can check that `l` and `r` have the same one by comparing the contained values (or use the small `ensure_equals!()` macro to do that)

**Comment by Nadrieril** [comment]
> Is there a good way of getting an overview of the codebase in general? Like generate the docs and look at the types and docs?

I just discovered `cargo doc --document-private-items`, which generates the docs of everything, even the private items. This could be useful to get an idea of the codebase, though private items are mostly undocumented.

**Comment by FintanH** [comment]
Oh ya, that works! We should add that to the README :)
