### ISSUE TITLE
Implement Type Check for `/\`

### ISSUE THREAD

**Issue by FintanH** [Nadrieril/dhall-rust#89]
The implementation of type-checking `Combine`/`RecursiveRecordMerge`

**Comment by FintanH** [comment]
@basile-henry @Nadrieril: I'm finally "fighting the borrow checker" and could use some guidance :sweat_smile: 

So this is my WIP: https://github.com/FintanH/dhall-rust/blob/fintan/typecheck-combine/dhall/src/phase/typecheck.rs#L601-L662 and it's _so close_.

The issue is that this line: https://github.com/FintanH/dhall-rust/blob/fintan/typecheck-combine/dhall/src/phase/typecheck.rs#L630 results in:
```
error[E0507]: cannot move out of borrowed content
   --> dhall/src/phase/typecheck.rs:630:45
    |
630 |                     kts.iter().map(|(x, v)| v.clone().map(|r| (x.clone(), r)))
    |                                             ^^^^^^^^^ cannot move out of borrowed content
```

**Comment by Nadrieril** [comment]
Hmm, this looks like a case of fighting the typechecker. My guess is that it's using the Clone instance of `&Result<>` instead of using the one of `Result<>` itself, which is what you expect. Maybe TypeError is not Clone ? References can always be cloned (in fact, they're even Copy), but of course you get the same reference at the other end, so it's useless.
Since you own `kts`, a good solution would be using `into_iter` instead of `iter` and then you don't even need to clone anything

**Comment by FintanH** [comment]
Oh my god, that worked :scream: I'll have to look into why those two differ :smile: I'll have a PR up for this ASAP :grin: Sorry for sniping it @basile-henry :sweat_smile:

**Comment by Nadrieril** [comment]
If I may explain a bit more: when you call `x.clone()` on an x of type `T`, rust will check if T is clone and call its Clone implementation.
If x is of type `&T`, the same will happen first. What happens if T is not Clone though ? Then rust will realize that `&T` is Clone (because references can always trivially be cloned), and just clone the reference. That's never what you want though, and you get a confusing error message.
In short, if x is a reference to a non-Clone thing, then `x.clone()` will confusingly be the same as `x`. In this case the `.map` methods wants a `Result` as input but you only have a `&Result`, so the compiler shouts at you. It's an annoying quirk that I got used to; hopefully they'll make the error less confusing in the future.

The difference between `iter` and `into_iter` is simple: `x.iter()` only looks at x and gives you references to what's inside; `x.into_iter()` destroys x and gives you what's inside directly. If x is a reference to a map, you're not allowed to change it so you can't call `into_iter()`. Here however you own kts so it works.

**Comment by FintanH** [comment]
Thanks @Nadrieril that makes perfect sense :grin: This has been a good learning experience :smile:
